"""
AerisVault - Report Generator
Generate HTML and PDF reports from analysis results.
"""

import pandas as pd
from pathlib import Path
from typing import Optional, Dict, List
from datetime import datetime
import base64
import io


class ReportGenerator:
    """Generate analysis reports."""
    
    @staticmethod
    def generate_html_report(
        df: pd.DataFrame,
        statistics: Dict,
        events: Optional[Dict] = None,
        output_path: Optional[Path] = None,
        title: str = "AerisVault Analysis Report"
    ) -> str:
        """
        Generate HTML report.
        
        Args:
            df: Analysis DataFrame
            statistics: Statistical analysis results
            events: Detected events
            output_path: Optional output file path
            title: Report title
            
        Returns:
            HTML content as string
        """
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 40px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            border-bottom: 1px solid #bdc3c7;
            padding-bottom: 5px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #3498db;
            color: white;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .metric {{
            display: inline-block;
            margin: 10px 20px 10px 0;
            padding: 15px;
            background-color: #ecf0f1;
            border-radius: 5px;
        }}
        .metric-label {{
            font-size: 12px;
            color: #7f8c8d;
            text-transform: uppercase;
        }}
        .metric-value {{
            font-size: 24px;
            font-weight: bold;
            color: #2c3e50;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #bdc3c7;
            text-align: center;
            color: #7f8c8d;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🪂 {title}</h1>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        
        <h2>📊 Summary Statistics</h2>
        <div>
"""
        
        # Add key metrics
        if statistics:
            stats_df = pd.DataFrame(statistics).T
            for col in ['mean', 'std', 'min', 'max']:
                if col in stats_df.columns:
                    html += f"""
            <div class="metric">
                <div class="metric-label">{col.upper()}</div>
                <div class="metric-value">{stats_df[col].mean():.2f}</div>
            </div>
"""
        
        html += """
        </div>
        
        <h2>📈 Detailed Statistics</h2>
"""
        
        # Add statistics table
        if statistics:
            stats_df = pd.DataFrame(statistics).T
            html += stats_df.to_html(classes='stats-table', float_format=lambda x: f'{x:.4f}')
        
        # Add events if available
        if events:
            html += "<h2>🎯 Detected Events</h2><ul>"
            
            if events.get('deployment', {}).get('detected'):
                deploy = events['deployment']
                html += f"<li><strong>Deployment:</strong> t = {deploy['deployment_time']:.3f}s, F = {deploy['deployment_force']:.2f}N</li>"
            
            if 'inflation' in events:
                inflation = events['inflation']
                html += f"<li><strong>Inflation Duration:</strong> {inflation['inflation_duration']:.3f}s</li>"
                html += f"<li><strong>Peak Force:</strong> {inflation['peak_force']:.2f}N at t = {inflation['peak_time']:.3f}s</li>"
            
            if events.get('steady_state', {}).get('detected'):
                steady = events['steady_state']
                html += f"<li><strong>Steady State Reached:</strong> t = {steady['steady_time']:.3f}s</li>"
            
            html += "</ul>"
        
        html += f"""
        <div class="footer">
            <p>Generated by AerisVault v0.2.0</p>
            <p>Advanced Analysis Tool for LS-DYNA ICFD Simulations</p>
        </div>
    </div>
</body>
</html>
"""
        
        # Save if output path provided
        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w') as f:
                f.write(html)
        
        return html
